[package]
name = "coherence-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
logger = { path = "../logger" }
tide = "0.16.0"
async-std = { version = "1.8.0", features = ["attributes"] }
serde = { version = "1.0", features = ["derive"] }
http-types = "2.12.0"
serde_json = "1.0.85"
