[package]
name = "coherence"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "cacher"

[dependencies]
clap = { version = "3.2.22", features = ["derive"] }
zip = "0.6.2"

